sudo: required
language: generic
servies:
  - docker

before_install:
  - docker build -t coffmanjrp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true coffmanjrp/react-test npm test

after_success:
  - docker build -t coffmanjrp/fibonacci-calculator-client ./client
  - docker build -t coffmanjrp/fibonacci-calculator-nginx ./nginx
  - docker build -t coffmanjrp/fibonacci-calculator-server ./server
  - docker build -t coffmanjrp/fibonacci-calculator-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push them to Docker Hub
  - docker push coffmanjrp/fibonacci-calculator-client
  - docker push coffmanjrp/fibonacci-calculator-nginx
  - docker push coffmanjrp/fibonacci-calculator-server
  - docker push coffmanjrp/fibonacci-calculator-worker
